#!/bin/bash
{ [[ -f repofns.sh ]] && . ./repofns.sh; } || { [[ -f ../repofns.sh ]] && . ../repofns.sh; }
cmd=(
	curl -s
		-H "Authorization: Bearer $GH_TOKEN"
		-H "Accept: application/vnd.github+json"
		'https://api.github.com/user/repos?visibility=all&affiliation=owner,collaborator,organization_member&per_page=100'
)
cmd_filt=(
	jq '[.[] | select(.owner.login != "'"$GH_LOGIN"'")]'
)

(
asection "Command:"
echo -n "$a_cmd "
printf '%q ' "${cmd[@]}"
echo -n "$rst"
echo '|'
echo -n "$a_cmd2  "
printf '%q ' "${cmd_filt[@]}"
echo "$rst"
) >&2

"${cmd[@]}" | "${cmd_filt[@]}"
